### ISSUE TITLE
TypeScript series 👌🏻

### ISSUE THREAD

**Issue by skovhus** [davetayls/davetayls.github.com#2]
Thanks for the typescript series. Looking forward following it. As a extensive user of Flow and React/React-Native, it is nice to see how TS works and offers. 

Btw, small typo in an headline "Component Prop and State Interafaces"

**Comment by davetayls** [comment]
hey @skovhus thanks. It's interesting seeing how Flow has influenced some of the TypeScript changes recently and this whole strongly typed genre of languages. I've got about 5 articles left in the series, so there are more gems to discover 😄 

thanks for the typo, i'll fix
